insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (1, 'Erin', 'Rumin', 'Services', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (2, 'Kamila', 'Mussett', 'Accounting', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (3, 'Currey', 'Sparshott', 'Engineering', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (4, 'Baird', 'MacClenan', 'Research and Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (5, 'Gerhard', 'Tsar', 'Product Management', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (6, 'Marya', 'Nowill', 'Services', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (7, 'Briney', 'Greaterex', 'Engineering', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (8, 'Tyrus', 'Birtwisle', 'Research and Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (9, 'Rollin', 'Sivill', 'Services', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (10, 'Chaddy', 'Kingsnod', 'Training', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (11, 'Finlay', 'Sparkwill', 'Support', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (12, 'Evvie', 'Woodhead', 'Human Resources', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (13, 'Burk', 'Queenborough', 'Accounting', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (14, 'Durand', 'Rainsden', 'Human Resources', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (15, 'Taber', 'Kenyon', 'Marketing', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (16, 'Garland', 'Sarver', 'Marketing', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (17, 'Mose', 'Soots', 'Business Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (18, 'Zara', 'Cassidy', 'Research and Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (19, 'Stearn', 'Henrique', 'Sales', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (20, 'Hurleigh', 'Blazi', 'Legal', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (21, 'Theodora', 'Beach', 'Business Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (22, 'Tabina', 'Fransewich', 'Product Management', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (23, 'Lulu', 'Shanklin', 'Training', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (24, 'Anabelle', 'Trymme', 'Accounting', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (25, 'Hallsy', 'Brise', 'Human Resources', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (26, 'Mabelle', 'Ivery', 'Research and Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (27, 'Elizabet', 'Klas', 'Engineering', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (28, 'Wolf', 'Buncom', 'Human Resources', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (29, 'Karita', 'Shervil', 'Support', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (30, 'Bernette', 'Steedman', 'Services', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (31, 'Inger', 'Behne', 'Human Resources', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (32, 'Korney', 'Tugman', 'Marketing', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (33, 'Yevette', 'MacFie', 'Legal', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (34, 'Tiff', 'Calderbank', 'Legal', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (35, 'Miltie', 'Banke', 'Business Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (36, 'Maris', 'Siggs', 'Legal', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (37, 'Madonna', 'Furmedge', 'Accounting', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (38, 'Durward', 'Jouanny', 'Research and Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (39, 'Marleen', 'Greiser', 'Sales', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (40, 'Pietrek', 'Delos', 'Training', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (41, 'Giles', 'Andrick', 'Marketing', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (42, 'Vevay', 'Letch', 'Product Management', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (43, 'Shayla', 'Kaley', 'Legal', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (44, 'Seward', 'Snufflebottom', 'Support', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (45, 'Whitman', 'Cuppleditch', 'Sales', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (46, 'Dayna', 'Mennithorp', 'Engineering', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (47, 'Franklin', 'Posten', 'Business Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (48, 'Nanine', 'Drysdall', 'Legal', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (49, 'Fritz', 'Stannering', 'Research and Development', 0);
insert into Employee (employeeId, firstName, lastName, role, dealershipId) values (50, 'Livy', 'Gosson', 'Sales', 0);
